/**
 * Economics Yojana — important Indian government schemes (Marathi notes)
 * --------------------------------------------------------------------
 * Source data lives in `economicsYojanaContent.json`, generated by
 * `scripts/extract_yojana_pdf.py` from the original Marathi handout. The
 * extractor strips publisher branding (academy name, city, mobile numbers)
 * so this site can host an independent, copy-protected revision sheet.
 *
 * This module wraps the JSON in strongly-typed exports consumed by the
 * `EconomicsYojanaNotes` reader and the Notes hub card.
 */

import raw from "./economicsYojanaContent.json";

export type YojanaItemKind = "para" | "subhead" | "date";

export type YojanaItem = {
  kind: YojanaItemKind;
  text: string;
};

export type YojanaGroup = {
  id: string;
  titleMr: string;
  titleEn: string;
  items: YojanaItem[];
};

export type YojanaMCQ = {
  /** 1-indexed question number from the original handout */
  n: number;
  q: string;
  /** Exam tag (e.g. "राज्यसेवा मुख्य २०१७"); may be null when absent */
  tag: string | null;
  opts: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
};

type Raw = {
  totalGroups: number;
  totalMcqs: number;
  groups: Array<{
    id: string;
    titleMr: string;
    titleEn: string;
    items: Array<{ kind: string; text: string }>;
  }>;
  stats: string[];
  mcqs: Array<{
    n: number;
    q: string;
    tag: string | null;
    opts: string[];
    correct: number;
  }>;
};

const data = raw as Raw;

export const YOJANA_GROUPS: YojanaGroup[] = data.groups.map((g) => ({
  id: g.id,
  titleMr: g.titleMr,
  titleEn: g.titleEn,
  items: g.items.map((it) => ({
    kind: (it.kind === "subhead" || it.kind === "date" ? it.kind : "para") as YojanaItemKind,
    text: it.text,
  })),
}));

export const YOJANA_STATS: string[] = data.stats;

export const YOJANA_MCQS: YojanaMCQ[] = data.mcqs.map((m) => ({
  n: m.n,
  q: m.q,
  tag: m.tag,
  opts: [
    m.opts[0] ?? "—",
    m.opts[1] ?? "—",
    m.opts[2] ?? "—",
    m.opts[3] ?? "—",
  ] as [string, string, string, string],
  correct: Math.max(0, Math.min(3, m.correct)) as 0 | 1 | 2 | 3,
}));

export const YOJANA_TOTAL_GROUPS = YOJANA_GROUPS.length;
export const YOJANA_TOTAL_ITEMS = YOJANA_GROUPS.reduce(
  (acc, g) => acc + g.items.length,
  0,
);
export const YOJANA_TOTAL_MCQS = YOJANA_MCQS.length;
