/**
 * Maharashtra Geography — chapter metadata.
 *
 * The original notes (by Lokseva Academy / Appa Hatnure Sir) live as 83
 * page-images under `/notes/mh-geography/pages/page-001.jpg` ...
 * `page-083.jpg`, generated by `scripts/build_mh_geography_redesign.py`.
 * This file is the authoritative TOC the React viewer renders against.
 */

export type MhGeoPart = {
  id: 1 | 2;
  label: string;
  titleEn: string;
  titleMr: string;
};

export type MhGeoChapter = {
  number: string;       // "01" .. "16"
  titleEn: string;
  titleMr: string;
  pageStart: number;    // 1-based source-PDF page
  pageEnd: number;      // inclusive
  part: 1 | 2;
  tip: string;          // 1-line study tip surfaced on the chapter card
};

export const MH_GEO_PARTS: MhGeoPart[] = [
  { id: 1, label: "Part 1", titleEn: "Maharashtra Geography",  titleMr: "महाराष्ट्र भूगोल" },
  { id: 2, label: "Part 2", titleEn: "Other Important Topics", titleMr: "इतर महत्त्वाचे घटक" },
];

export const MH_GEO_CHAPTERS: MhGeoChapter[] = [
  { number: "01", titleEn: "Formation of Maharashtra",        titleMr: "महाराष्ट्राची स्थापना",                pageStart: 2,  pageEnd: 2,  part: 1, tip: "Pin down 1 May 1960 and the Bombay Reorganisation Act." },
  { number: "02", titleEn: "Location, Extent & Shape",        titleMr: "महाराष्ट्र : स्थान, विस्तार व आकार",   pageStart: 3,  pageEnd: 4,  part: 1, tip: "Memorise the lat/long extents — both India & Maharashtra." },
  { number: "03", titleEn: "Political Geography",             titleMr: "महाराष्ट्राचा राजकीय भूगोल",            pageStart: 5,  pageEnd: 9,  part: 1, tip: "Map the 6 revenue divisions to their 36 districts." },
  { number: "04", titleEn: "Structural Physical Geography",   titleMr: "रचनात्मक प्राकृतिक भूगोल",            pageStart: 10, pageEnd: 14, part: 1, tip: "Learn the 4 physiographic divisions and their highest peaks." },
  { number: "05", titleEn: "Census of India & Maharashtra",   titleMr: "भारताची व महाराष्ट्राची जनगणना",        pageStart: 15, pageEnd: 23, part: 1, tip: "Memorise the 2011 census top-10 lists for Maharashtra." },
  { number: "06", titleEn: "Migration",                       titleMr: "स्थलांतर",                            pageStart: 24, pageEnd: 24, part: 1, tip: "Push & pull factors with classic Indian examples." },
  { number: "07", titleEn: "River Systems",                   titleMr: "नदीप्रणाली",                          pageStart: 25, pageEnd: 36, part: 1, tip: "Master Krishna, Godavari, Tapi, and the Konkan rivers." },
  { number: "08", titleEn: "Mineral Wealth",                  titleMr: "खनिज संपत्ती",                         pageStart: 37, pageEnd: 40, part: 1, tip: "Mineral districts → Nagpur (Mn), Chandrapur (Coal)." },
  { number: "09", titleEn: "Climate",                         titleMr: "हवामान",                              pageStart: 41, pageEnd: 47, part: 1, tip: "Climatic divisions: Konkan, Western Maharashtra, Marathwada, Vidarbha." },
  { number: "10", titleEn: "Forests",                         titleMr: "वनसंपत्ती",                           pageStart: 48, pageEnd: 57, part: 1, tip: "Reserved forests, biosphere reserves & 6 tiger reserves." },
  { number: "11", titleEn: "Energy Resources",                titleMr: "महाराष्ट्रातील ऊर्जा साधनसंपत्ती",        pageStart: 58, pageEnd: 63, part: 1, tip: "Hydro / Thermal / Nuclear plant locations + capacities." },
  { number: "12", titleEn: "Transport & Communication",       titleMr: "वाहतूक व दळणवळण",                  pageStart: 64, pageEnd: 70, part: 1, tip: "National highways through Maharashtra & major ports." },
  { number: "13", titleEn: "Tourism",                         titleMr: "पर्यटन",                              pageStart: 71, pageEnd: 73, part: 1, tip: "World Heritage sites: Ajanta, Ellora, Elephanta, CSMT." },
  { number: "14", titleEn: "Astronomy",                       titleMr: "खगोलशास्त्र",                          pageStart: 74, pageEnd: 78, part: 2, tip: "Solar system order, planet records, Indian space milestones." },
  { number: "15", titleEn: "Atmosphere",                      titleMr: "वातावरण",                             pageStart: 79, pageEnd: 81, part: 2, tip: "Atmospheric layers in order of altitude." },
  { number: "16", titleEn: "Space Launches",                  titleMr: "अवकाश प्रक्षेपण",                     pageStart: 82, pageEnd: 83, part: 2, tip: "ISRO chronology — SLV, ASLV, PSLV, GSLV, GSLV-Mk III, SSLV." },
];

export const MH_GEO_TOTAL_PAGES = 83;
export const MH_GEO_PDF_HREF =
  "/notes/mh-geography/maharashtra-geography-redesigned.pdf";
export const MH_GEO_IMAGE_HREF = (page: number) =>
  `/notes/mh-geography/pages/page-${String(page).padStart(3, "0")}.jpg`;
