/**
 * Modern Maharashtra History — Marathi notes
 * --------------------------------------------------------------------
 * Source data lives in `mhHistoryContent.json`, generated by
 * `scripts/extract_mh_history_pdf.py` from the original Marathi handout.
 * The extractor strips publisher branding (author tagline, telegram
 * channel, contact number, "[Year]" header, repeated chapter banner)
 * so this site can host an independent, copy-protected revision sheet.
 *
 * This module wraps the JSON in strongly-typed exports consumed by the
 * `MhHistoryNotes` reader and the Notes hub card.
 */

import raw from "./mhHistoryContent.json";

export type MhHistoryBlockKind = "para" | "subhead" | "bullet" | "info";

export type MhHistoryBlock = {
  kind: MhHistoryBlockKind;
  text: string;
};

export type MhHistoryChapter = {
  id: string;
  icon: string;
  /** Tailwind gradient applied to the chapter's hero strip & chip */
  accent: string;
  titleMr: string;
  titleEn: string;
  subtitleMr: string;
  /** One-line revision tip rendered under the chapter title */
  tip: string;
  pageStart: number;
  pageEnd: number;
  blocks: MhHistoryBlock[];
};

type Raw = {
  title_mr: string;
  title_en: string;
  subtitle_mr: string;
  totalPages: number;
  totalChapters: number;
  totalBlocks: number;
  chapters: Array<{
    id: string;
    icon: string;
    accent: string;
    titleMr: string;
    titleEn: string;
    subtitleMr: string;
    tip: string;
    pageStart: number;
    pageEnd: number;
    blocks: Array<{ kind: string; text: string }>;
  }>;
};

const data = raw as Raw;

const ALLOWED_KINDS = new Set<MhHistoryBlockKind>([
  "para",
  "subhead",
  "bullet",
  "info",
]);

export const MH_HISTORY_TITLE_MR: string = data.title_mr;
export const MH_HISTORY_TITLE_EN: string = data.title_en;
export const MH_HISTORY_SUBTITLE_MR: string = data.subtitle_mr;
export const MH_HISTORY_TOTAL_PAGES: number = data.totalPages;

export const MH_HISTORY_CHAPTERS: MhHistoryChapter[] = data.chapters.map(
  (c) => ({
    id: c.id,
    icon: c.icon,
    accent: c.accent,
    titleMr: c.titleMr,
    titleEn: c.titleEn,
    subtitleMr: c.subtitleMr,
    tip: c.tip,
    pageStart: c.pageStart,
    pageEnd: c.pageEnd,
    blocks: c.blocks.map((b) => ({
      kind: (ALLOWED_KINDS.has(b.kind as MhHistoryBlockKind)
        ? b.kind
        : "para") as MhHistoryBlockKind,
      text: b.text,
    })),
  }),
);

export const MH_HISTORY_TOTAL_CHAPTERS = MH_HISTORY_CHAPTERS.length;

export const MH_HISTORY_TOTAL_BLOCKS = MH_HISTORY_CHAPTERS.reduce(
  (acc, c) => acc + c.blocks.length,
  0,
);

/** Count of just the bullet blocks across the whole pack — useful for the
 *  hub card's at-a-glance metric. */
export const MH_HISTORY_TOTAL_BULLETS = MH_HISTORY_CHAPTERS.reduce(
  (acc, c) => acc + c.blocks.filter((b) => b.kind === "bullet").length,
  0,
);
