/**
 * समाजसुधारक — detailed Marathi revision notes
 * --------------------------------------------
 * Curated from handwritten handouts (samajsudharak 1 & 2 PDFs).
 * Content lives in `samajsudharakContent.json` (generated by
 * `scripts/build_samajsudharak_notes.py`).
 * Portraits: Wikimedia Commons / Wikipedia free page images where available.
 */

import raw from "./samajsudharakContent.json";

export type SamajBlockKind = "para" | "subhead" | "bullet" | "info";

export type SamajBlock = {
  kind: SamajBlockKind;
  text: string;
};

export type SamajChapter = {
  id: string;
  /** Local path under /public, e.g. /notes/samajsudharak/ambedkar.jpg */
  image: string | null;
  accent: string;
  titleMr: string;
  titleEn: string;
  subtitleMr: string;
  tip: string;
  blocks: SamajBlock[];
};

type Raw = {
  title_mr: string;
  title_en: string;
  subtitle_mr: string;
  totalPages: number;
  totalChapters: number;
  totalBlocks: number;
  chapters: Array<{
    id: string;
    image?: string | null;
    accent: string;
    titleMr: string;
    titleEn: string;
    subtitleMr: string;
    tip: string;
    blocks: Array<{ kind: string; text: string }>;
  }>;
};

const data = raw as Raw;

export const SAMAJ_TITLE_MR = data.title_mr;
/** @deprecated English title removed — notes are Marathi-only */
export const SAMAJ_TITLE_EN = data.title_en || "";
export const SAMAJ_SUBTITLE_MR = data.subtitle_mr;
export const SAMAJ_TOTAL_PAGES = data.totalPages;
export const SAMAJ_TOTAL_CHAPTERS = data.totalChapters;
export const SAMAJ_TOTAL_BULLETS = data.totalBlocks;

export const SAMAJ_CHAPTERS: SamajChapter[] = data.chapters.map((c) => ({
  id: c.id,
  image: c.image ?? null,
  accent: c.accent,
  titleMr: c.titleMr,
  titleEn: c.titleEn,
  subtitleMr: c.subtitleMr,
  tip: c.tip,
  blocks: c.blocks.map((b) => ({
    kind: b.kind as SamajBlockKind,
    text: b.text,
  })),
}));
